forecast = {
    "location": {
        "name": "London",
        "region": "City of London, Greater London",
        "country": "United Kingdom",
        "lat": 51.52,
        "lon": -0.11,
        "tz_id": "Europe/London",
        "localtime_epoch": 1716016271,
        "localtime": "2024-05-18 8:11",
    },
    "current": {
        "last_updated_epoch": 1716015600,
        "last_updated": "2024-05-18 08:00",
        "temp_c": 13.0,
        "temp_f": 55.4,
        "is_day": 1,
        "condition": {
            "text": "Partly cloudy",
            "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
            "code": 1003,
        },
        "wind_mph": 8.1,
        "wind_kph": 13.0,
        "wind_degree": 30,
        "wind_dir": "NNE",
        "pressure_mb": 1013.0,
        "pressure_in": 29.91,
        "precip_mm": 0.0,
        "precip_in": 0.0,
        "humidity": 88,
        "cloud": 75,
        "feelslike_c": 12.7,
        "feelslike_f": 54.8,
        "vis_km": 10.0,
        "vis_miles": 6.0,
        "uv": 3.0,
        "gust_mph": 12.5,
        "gust_kph": 20.2,
    },
    "forecast": {
        "forecastday": [
            {
                "date": "2024-05-18",
                "date_epoch": 1715990400,
                "day": {
                    "maxtemp_c": 20.0,
                    "maxtemp_f": 68.0,
                    "mintemp_c": 11.4,
                    "mintemp_f": 52.6,
                    "avgtemp_c": 15.3,
                    "avgtemp_f": 59.5,
                    "maxwind_mph": 7.8,
                    "maxwind_kph": 12.6,
                    "totalprecip_mm": 2.21,
                    "totalprecip_in": 0.09,
                    "totalsnow_cm": 0.0,
                    "avgvis_km": 8.3,
                    "avgvis_miles": 5.0,
                    "avghumidity": 82,
                    "daily_will_it_rain": 1,
                    "daily_chance_of_rain": 83,
                    "daily_will_it_snow": 0,
                    "daily_chance_of_snow": 0,
                    "condition": {
                        "text": "Patchy rain nearby",
                        "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                        "code": 1063,
                    },
                    "uv": 5.0,
                },
            },
            {
                "date": "2024-05-19",
                "date_epoch": 1716076800,
                "day": {
                    "maxtemp_c": 21.5,
                    "maxtemp_f": 70.7,
                    "mintemp_c": 9.5,
                    "mintemp_f": 49.0,
                    "avgtemp_c": 15.2,
                    "avgtemp_f": 59.3,
                    "maxwind_mph": 10.5,
                    "maxwind_kph": 16.9,
                    "totalprecip_mm": 0.63,
                    "totalprecip_in": 0.02,
                    "totalsnow_cm": 0.0,
                    "avgvis_km": 8.3,
                    "avgvis_miles": 5.0,
                    "avghumidity": 75,
                    "daily_will_it_rain": 1,
                    "daily_chance_of_rain": 81,
                    "daily_will_it_snow": 0,
                    "daily_chance_of_snow": 0,
                    "condition": {
                        "text": "Patchy rain nearby",
                        "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                        "code": 1063,
                    },
                    "uv": 6.0,
                },
            },
            {
                "date": "2024-05-20",
                "date_epoch": 1716163200,
                "day": {
                    "maxtemp_c": 20.2,
                    "maxtemp_f": 68.4,
                    "mintemp_c": 9.2,
                    "mintemp_f": 48.5,
                    "avgtemp_c": 14.7,
                    "avgtemp_f": 58.4,
                    "maxwind_mph": 11.2,
                    "maxwind_kph": 18.0,
                    "totalprecip_mm": 0.16,
                    "totalprecip_in": 0.01,
                    "totalsnow_cm": 0.0,
                    "avgvis_km": 10.0,
                    "avgvis_miles": 6.0,
                    "avghumidity": 66,
                    "daily_will_it_rain": 1,
                    "daily_chance_of_rain": 81,
                    "daily_will_it_snow": 0,
                    "daily_chance_of_snow": 0,
                    "condition": {
                        "text": "Patchy rain nearby",
                        "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                        "code": 1063,
                    },
                    "uv": 6.0,
                },
            },
            {
                "date": "2024-05-21",
                "date_epoch": 1716249600,
                "day": {
                    "maxtemp_c": 20.2,
                    "maxtemp_f": 68.3,
                    "mintemp_c": 8.4,
                    "mintemp_f": 47.2,
                    "avgtemp_c": 13.9,
                    "avgtemp_f": 57.1,
                    "maxwind_mph": 6.7,
                    "maxwind_kph": 10.8,
                    "totalprecip_mm": 3.75,
                    "totalprecip_in": 0.15,
                    "totalsnow_cm": 0.0,
                    "avgvis_km": 9.7,
                    "avgvis_miles": 6.0,
                    "avghumidity": 73,
                    "daily_will_it_rain": 1,
                    "daily_chance_of_rain": 89,
                    "daily_will_it_snow": 0,
                    "daily_chance_of_snow": 0,
                    "condition": {
                        "text": "Patchy rain nearby",
                        "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                        "code": 1063,
                    },
                    "uv": 5.0,
                },
            },
            {
                "date": "2024-05-22",
                "date_epoch": 1716336000,
                "day": {
                    "maxtemp_c": 17.7,
                    "maxtemp_f": 63.8,
                    "mintemp_c": 12.5,
                    "mintemp_f": 54.4,
                    "avgtemp_c": 14.6,
                    "avgtemp_f": 58.2,
                    "maxwind_mph": 7.6,
                    "maxwind_kph": 12.2,
                    "totalprecip_mm": 4.36,
                    "totalprecip_in": 0.17,
                    "totalsnow_cm": 0.0,
                    "avgvis_km": 6.8,
                    "avgvis_miles": 4.0,
                    "avghumidity": 86,
                    "daily_will_it_rain": 1,
                    "daily_chance_of_rain": 89,
                    "daily_will_it_snow": 0,
                    "daily_chance_of_snow": 0,
                    "condition": {
                        "text": "Patchy rain nearby",
                        "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                        "code": 1063,
                    },
                    "uv": 4.0,
                },
            },
            {
                "date": "2024-05-23",
                "date_epoch": 1716422400,
                "day": {
                    "maxtemp_c": 17.8,
                    "maxtemp_f": 64.1,
                    "mintemp_c": 10.4,
                    "mintemp_f": 50.7,
                    "avgtemp_c": 14.2,
                    "avgtemp_f": 57.6,
                    "maxwind_mph": 9.4,
                    "maxwind_kph": 15.1,
                    "totalprecip_mm": 0.8,
                    "totalprecip_in": 0.03,
                    "totalsnow_cm": 0.0,
                    "avgvis_km": 7.9,
                    "avgvis_miles": 4.0,
                    "avghumidity": 78,
                    "daily_will_it_rain": 1,
                    "daily_chance_of_rain": 88,
                    "daily_will_it_snow": 0,
                    "daily_chance_of_snow": 0,
                    "condition": {
                        "text": "Patchy rain nearby",
                        "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                        "code": 1063,
                    },
                    "uv": 3.0,
                },
            },
            {
                "date": "2024-05-24",
                "date_epoch": 1716508800,
                "day": {
                    "maxtemp_c": 17.8,
                    "maxtemp_f": 64.0,
                    "mintemp_c": 10.5,
                    "mintemp_f": 50.9,
                    "avgtemp_c": 14.5,
                    "avgtemp_f": 58.1,
                    "maxwind_mph": 6.0,
                    "maxwind_kph": 9.7,
                    "totalprecip_mm": 0.09,
                    "totalprecip_in": 0.0,
                    "totalsnow_cm": 0.0,
                    "avgvis_km": 10.0,
                    "avgvis_miles": 6.0,
                    "avghumidity": 76,
                    "daily_will_it_rain": 0,
                    "daily_chance_of_rain": 0,
                    "daily_will_it_snow": 0,
                    "daily_chance_of_snow": 0,
                    "condition": {
                        "text": "Patchy rain nearby",
                        "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                        "code": 1063,
                    },
                    "uv": 3.0,
                },
            },
            {
                "date": "2024-05-25",
                "date_epoch": 1716595200,
                "day": {
                    "maxtemp_c": 20.5,
                    "maxtemp_f": 69.0,
                    "mintemp_c": 11.4,
                    "mintemp_f": 52.6,
                    "avgtemp_c": 16.1,
                    "avgtemp_f": 61.0,
                    "maxwind_mph": 9.6,
                    "maxwind_kph": 15.5,
                    "totalprecip_mm": 0.04,
                    "totalprecip_in": 0.0,
                    "totalsnow_cm": 0.0,
                    "avgvis_km": 10.0,
                    "avgvis_miles": 6.0,
                    "avghumidity": 68,
                    "daily_will_it_rain": 0,
                    "daily_chance_of_rain": 0,
                    "daily_will_it_snow": 0,
                    "daily_chance_of_snow": 0,
                    "condition": {
                        "text": "Partly Cloudy ",
                        "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                        "code": 1003,
                    },
                    "uv": 5.0,
                },
            },
            {
                "date": "2024-05-26",
                "date_epoch": 1716681600,
                "day": {
                    "maxtemp_c": 20.0,
                    "maxtemp_f": 68.0,
                    "mintemp_c": 12.2,
                    "mintemp_f": 54.0,
                    "avgtemp_c": 16.4,
                    "avgtemp_f": 61.6,
                    "maxwind_mph": 9.4,
                    "maxwind_kph": 15.1,
                    "totalprecip_mm": 1.63,
                    "totalprecip_in": 0.06,
                    "totalsnow_cm": 0.0,
                    "avgvis_km": 9.0,
                    "avgvis_miles": 5.0,
                    "avghumidity": 78,
                    "daily_will_it_rain": 1,
                    "daily_chance_of_rain": 86,
                    "daily_will_it_snow": 0,
                    "daily_chance_of_snow": 0,
                    "condition": {
                        "text": "Patchy rain nearby",
                        "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                        "code": 1063,
                    },
                    "uv": 4.0,
                },
            },
            {
                "date": "2024-05-27",
                "date_epoch": 1716768000,
                "day": {
                    "maxtemp_c": 20.2,
                    "maxtemp_f": 68.4,
                    "mintemp_c": 14.2,
                    "mintemp_f": 57.6,
                    "avgtemp_c": 16.5,
                    "avgtemp_f": 61.8,
                    "maxwind_mph": 6.0,
                    "maxwind_kph": 9.7,
                    "totalprecip_mm": 5.73,
                    "totalprecip_in": 0.23,
                    "totalsnow_cm": 0.0,
                    "avgvis_km": 8.6,
                    "avgvis_miles": 5.0,
                    "avghumidity": 90,
                    "daily_will_it_rain": 1,
                    "daily_chance_of_rain": 87,
                    "daily_will_it_snow": 0,
                    "daily_chance_of_snow": 0,
                    "condition": {
                        "text": "Moderate rain",
                        "icon": "//cdn.weatherapi.com/weather/64x64/day/302.png",
                        "code": 1189,
                    },
                    "uv": 4.0,
                },
            },
        ]
    },
}
